#include "wwfcBase.hpp"

#include "wwfcError.cpp"
#include "wwfcGPReport.cpp"
#include "wwfcHostPlatform.cpp"
#include "wwfcLibC.cpp"
#include "wwfcLogin.cpp"
#include "wwfcMii.cpp"
#include "wwfcNatneg.cpp"
#include "wwfcPatch.cpp"
#include "wwfcPayload.cpp"
#include "wwfcProcess.cpp"
#include "wwfcSecurity.cpp"
#include "wwfcSupport.cpp"

#include "mkwAntiFreeze.cpp"
#include "mkwBugFix.cpp"
#include "mkwFeature.cpp"
#include "mkwOpenHostPage.cpp"
#include "mkwSecurity.cpp"
#include "mkwTime.cpp"
