#include "game/RMC.h"

#include "wwfcAntiFreeze.cpp"
#include "wwfcFeature.cpp"
#include "wwfcLibC.cpp"
#include "wwfcLogin.cpp"
#include "wwfcMii.cpp"
#include "wwfcPatch.cpp"
#include "wwfcPayload.cpp"
#include "wwfcSecurity.cpp"
#include "wwfcSupport.cpp"
